# Generated by Django 4.0.1 on 2022-01-30 17:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=256)),
                ('userid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('business', 'business account'), ('personal', 'Personal account')], max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
