# Generated by Django 4.0.1 on 2022-02-04 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_account',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default=123, max_length=256),
        ),
        migrations.AlterField(
            model_name='topup',
            name='wallet_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.wallet'),
        ),
        migrations.AlterField(
            model_name='user_account',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.users'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('photo', models.ImageField(upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
